### ISSUE TITLE
not the right version

### ISSUE THREAD

**Issue by skinnykoala6** [inayakitori/4dmc#58] opened 2024-01-09 04:27 UTC
I have a modpack that is using 1.20.1 and I would like to add this mod. Is there any way you could add a version compatible with 1.20.1? None of the other versions will work.

**Comment by inayakitori** [comment] 2024-01-09 04:30
duplicate of #39 . please search existing issues before creating one

**Comment by skinnykoala6** [comment] 2024-01-09 04:30
okay i just did.

**Closed by inayakitori** 2024-01-09 04:30 UTC
Labels: duplicate
